### ISSUE TITLE
Galerie lädt Bilder nicht immer

### ISSUE THREAD

**Issue by BastianWerner** [Skyl0/bw_2016#29]
Hallo Marc,

mal zeigt die Galerie die Bilder und mal nicht. Auch nach dem Chache leeren gleicher Fehler.

Grüße

**Comment by Skyl0** [comment]
Bug ist bekannt, hab dem Support deswegen geschrieben, weil ich das Lightbox Plugin eigentlich ganz nett finde. Scheint aber ein Fehler in deren Code zu sein. Deswegen DUPLICATE weil ich den schon unten aufgeführt hab!
