### ISSUE TITLE
Kategorien für den Blog anlegen und Auswahlmenü einfügen!

### ISSUE THREAD

**Issue by BastianWerner** [Skyl0/bw_2016#30]
Hallo Marc,

ist es möglich Kategorien für den Blog anzulegen? Ich habe ja verschiedene Arten von Berichten.
zum Beispiel:
- Gewitter
- Sturm
- Landschaftsfotos
- Fotoreise
- Produktempfehlung

Es wäre cool, wenn jetzt ein Nutzer auf den Blog geht, welcher sich nur für bestimmte Berichte interessiert, eine Kategorie auswählen könnte und dann nur Berichte von dieser Art angezeigt bekommt.

**Comment by Skyl0** [comment]
Kategorien sind möglich klar! Allgemein ist momentan schon angelegt, ich lege die anderen noch an!

**Comment by Skyl0** [comment]
habs implementiert, closed
