### ISSUE TITLE
[Gallery] Bilder die für die oberste Gallerie Seite benutzt werden sollen aussuchen

### ISSUE THREAD

**Issue by Skyl0** [Skyl0/bw_2016#40]
Ich brauche die Bilder die du für die Übersicht haben willst.

Am besten 4:3 beschnitten bereits oder jenachdem 1:1 wenn du Quadratisch willst.
Dann kann ich das Overlay so anpassen dass du deine Ansicht hast.

**Comment by Skyl0** [comment]
Bitte die lange Kante (breite) 430px machen!

**Comment by BastianWerner** [comment]
Oke, mach ein Feld mit 2x4 Kacheln.

Folgende Sortierung:

Superzellen | Gewitterfronten
Blitze | Nachthimmel
Nebel | Himmelsröte
Berge | Küste

Bilder kommen gleich!

**Comment by BastianWerner** [comment]
Und quadratisch sollte es sein :)
