### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by BastianWerner** [Skyl0/bw_2016#42]
Eine Möglichkeit, den Nutzern einen Link zu geben, wo diese die Eintrittskarte kaufen können fehlt :)

Und zudem bleibt das eine Feld bei "Eintritt" frei.

http://www.bastianw.com/wordpress/event/seminar-wettervorhersage-fuer-landschaftsfotografen/

**Comment by Skyl0** [comment]
Wo willst du den Link haben ? Wo soll der Hinführen? Willst du eine Eintrittskarte kaufen Seite auf deiner eigenen Page haben mit nem Formular. Musst schon etwas präziser werden.

**Comment by Skyl0** [comment]
Besprochen: Link per Hand einfügen, da keine Funktion im Event Plugin vorliegt.
